version: '3.9'
services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - USER_SERVICE_URL=http://user-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3002
      - ORDER_SERVICE_URL=http://order-service:3003
      - PAYMENT_SERVICE_URL=http://payment-service:3004
      - JWT_SECRET="duUlkw8n1sCKmOwznJ0373lV1IoIsSdUjt5+mPZEn54="
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:38KC%24%25S8V4M9JwS@db.vdirafzcvmbdltbepgcp.supabase.co:5432/postgres
      - JWT_SECRET="duUlkw8n1sCKmOwznJ0373lV1IoIsSdUjt5+mPZEn54="
      - SESSION_SECRET="BFHjuM3c8LYJRJ8ixfxcxcJ83GylZQ/4cBKCXWIQP0w="
      - DISCORD_CLIENT_ID="1390240283316195358"
      - DISCORD_CLIENT_SECRET="kvCIj1ytgcn7uiT7SdQQ_4QyxBfvlDSs"
      - DISCORD_CALLBACK_URL=http://localhost:3000/api/auth/discord/callback
      - PRISMA_SCHEMA_PATH=../prisma/schema.prisma

  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    container_name: product-service
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgresql://postgres:38KC%24%25S8V4M9JwS@db.vdirafzcvmbdltbepgcp.supabase.co:5432/postgres
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - PRISMA_SCHEMA_PATH=../prisma/schema.prisma

  order-service:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    container_name: order-service
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq

  payment-service:
    build:
      context: .
      dockerfile: ./payment-service/Dockerfile
    container_name: payment-service
    ports:
      - "3004:3004"
    environment:
      - DATABASE_URL=postgresql://postgres:38KC%24%25S8V4M9JwS@db.vdirafzcvmbdltbepgcp.supabase.co:5432/postgres
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - SOLANA_RPC_URL=https://api.devnet.solana.com
      - SHOP_WALLET_ADDRESS=
      - PRISMA_SCHEMA_PATH=../prisma/schema.prisma

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
