version: '3.9'
services:
  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile # Consistent dockerfile path
    container_name: api-gateway # Corrected container name
    ports:
      - "3000:3000"
    env_file: # Added for consistency with other services
      - .env
    environment:
      - USER_SERVICE_URL=http://user-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3002
      - ORDER_SERVICE_URL=http://order-service:3003
      - PAYMENT_SERVICE_URL=http://payment-service:3004
      - JWT_SECRET="duUlkw8n1sCKmOwznJ0373lV1IoIsSdUjt5+mPZEn54="
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service
      - prisma-migrate # Added dependency to ensure migrations run first

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - JWT_SECRET="duUlkw8n1sCKmOwznJ0373lV1IoIsSdUjt5+mPZEn54="
      - SESSION_SECRET="BFHjuM3c8LYJRJ8ixfxcxcJ83GylZQ/4cBKCXWIQP0w="
      - DISCORD_CLIENT_ID=1390240283316195358
      - DISCORD_CLIENT_SECRET=kvCIj1ytgcn7uiT7SdQQ_4QyxBfvlDSs
      - DISCORD_CALLBACK_URL=http://localhost:3000/api/auth/discord/callback
    depends_on:
      - prisma-migrate # Added dependency to ensure migrations run first

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: product-service
    ports:
      - "3002:3002"
    env_file:
      - .env
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - SUPABASE_URL=https://vdirafzcvmbdltbepgcp.supabase.co
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkaXJhZnpjdm1iZGx0YmVwZ2NwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTc5Njc3OSwiZXhwIjoyMDY3MzcyNzc5fQ.whDAK773Un7qVBGhy-xl9qvk49DXwQIwggeX37Ra3oM
    depends_on:
      - prisma-migrate # Added dependency to ensure migrations run first

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    ports:
      - "3003:3003"
    env_file:
      - .env
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - JWT_SECRET="duUlkw8n1sCKmOwznJ0373lV1IoIsSdUjt5+mPZEn54="
    depends_on:
      - rabbitmq
      - prisma-migrate # Added dependency to ensure migrations run first

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    container_name: payment-service
    ports:
      - "3004:3004"
    env_file:
      - .env
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - SOLANA_RPC_URL=https://api.devnet.solana.com
      - SHOP_WALLET_ADDRESS=
    depends_on:
      - rabbitmq
      - prisma-migrate # Added dependency to ensure migrations run first

  prisma-migrate:
    build:
      context: .
      dockerfile: ./prisma-db/Dockerfile
    container_name: prisma-migrate
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest