services:
  - type: web
    name: api-gateway
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: USER_SERVICE_URL
        fromService:
          type: web
          name: user-service
          property: url
      - key: PRODUCT_SERVICE_URL
        fromService:
          type: web
          name: product-service
          property: url
      - key: ORDER_SERVICE_URL
        fromService:
          type: web
          name: order-service
          property: url
      - key: PAYMENT_SERVICE_URL
        fromService:
          type: web
          name: payment-service
          property: url
      - key: JWT_SECRET
        sync: false
    autoDeploy: true
    rootDir: api-gateway

  - type: web
    name: user-service
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate --schema=./prisma-db/prisma/schema.prisma
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: prisma-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_CALLBACK_URL
        sync: false
    autoDeploy: true
    rootDir: user-service

  - type: web
    name: product-service
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate --schema=./prisma-db/prisma/schema.prisma
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: prisma-db
          property: connectionString
      - key: RABBITMQ_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
    autoDeploy: true
    rootDir: product-service

  - type: web
    name: order-service
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate --schema=./prisma-db/prisma/schema.prisma
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: prisma-db
          property: connectionString
      - key: RABBITMQ_URL
        sync: false
    autoDeploy: true
    rootDir: order-service

  - type: web
    name: payment-service
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate --schema=./prisma-db/prisma/schema.prisma
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: prisma-db
          property: connectionString
      - key: RABBITMQ_URL
        sync: false
      - key: SOLANA_RPC_URL
        sync: false
      - key: SHOP_WALLET_ADDRESS
        sync: false
    autoDeploy: true
    rootDir: payment-service

  - type: worker
    name: prisma-migrate
    env: node
    plan: free
    buildCommand: npm install -g prisma
    startCommand: npx prisma migrate deploy --schema=./prisma/schema.prisma
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: prisma-db
          property: connectionString
    autoDeploy: true
    rootDir: prisma-db

  - type: pserv
    name: prisma-db
    env: node
    plan: free